/**
 * Legal pages: i18n EN/ES + dark mode toggle.
 * Shared by privacy.html, terms.html, cookies.html, data-deletion.html.
 */
(function () {
  const T = {
    en: {
      'nav.back': 'Back to Home',
      'legal.label': 'Legal',
      'footer.privacy': 'Privacy',
      'footer.terms': 'Terms',
      'footer.cookies': 'Cookies',
      'footer.dataDeletion': 'Data Deletion',
      'footer.copyright': '© 2026 SynapticSpark. All rights reserved.',

      // PRIVACY
      'privacy.title': 'Privacy Policy',
      'privacy.updated': 'Last updated: April 25, 2026',
      'privacy.intro': 'SynapticSpark ("we", "us", "our") respects your privacy. This Privacy Policy explains how we collect, use, share, and protect personal information when you use the SynapticSpark platform, our website, mobile applications, integrations (including the SynapticSpark Shopify app), APIs, and related services (collectively, the "Service").',
      'privacy.s1.title': '1. Information We Collect',
      'privacy.s1a.title': '1.1 Information you provide',
      'privacy.s1a.l1': 'Account data: name, email address, password (hashed), company name, phone number.',
      'privacy.s1a.l2': 'Billing data: payment details processed by our payment provider (we do not store full card numbers).',
      'privacy.s1a.l3': 'Content you upload: posts, images, videos, prompts, brand assets, keywords, and configuration.',
      'privacy.s1a.l4': 'Support communications: messages and metadata when you contact us.',
      'privacy.s1b.title': '1.2 Information from connected platforms',
      'privacy.s1b.intro': 'When you connect a third-party service (Shopify, Google Search Console, Meta, Instagram, Facebook, WhatsApp, Google Ads, TikTok Ads, Google Analytics, etc.) we receive the data you authorize, which may include:',
      'privacy.s1b.l1': 'Shopify: store domain, blog and article data, store metadata, OAuth access token (encrypted at rest).',
      'privacy.s1b.l2': 'Google Search Console: site properties, search queries, impressions, clicks, positions.',
      'privacy.s1b.l3': 'Social platforms: page IDs, posts, comments, messages, public profile data of users interacting with your channels.',
      'privacy.s1b.l4': 'Advertising platforms: campaigns, ad sets, performance metrics, audience data.',
      'privacy.s1b.note': 'We do not collect end-customer data from your Shopify store beyond what is required to deliver the SEO publishing functionality (blogs, articles). We do not access customer personally identifiable information stored in your Shopify customer base.',
      'privacy.s1c.title': '1.3 Information collected automatically',
      'privacy.s1c.l1': 'Usage data: pages visited, features used, timestamps.',
      'privacy.s1c.l2': 'Device data: browser, OS, IP address, language.',
      'privacy.s1c.l3': 'Cookies and similar technologies (see our Cookie Policy).',
      'privacy.s2.title': '2. How We Use Information',
      'privacy.s2.l1': 'Provide, operate, and improve the Service.',
      'privacy.s2.l2': 'Generate AI content based on your prompts and connected data sources.',
      'privacy.s2.l3': 'Publish content to platforms you have authorized (e.g. Shopify blogs).',
      'privacy.s2.l4': 'Authenticate users and prevent fraud or abuse.',
      'privacy.s2.l5': 'Communicate transactional notices, security alerts, and product updates.',
      'privacy.s2.l6': 'Comply with legal obligations.',
      'privacy.s3.title': '3. Legal Basis (GDPR)',
      'privacy.s3.body': 'If you are in the European Economic Area, United Kingdom, or Switzerland, our legal bases are: (i) performance of a contract; (ii) your consent (which you may withdraw); (iii) legitimate interests in operating and securing the Service; and (iv) compliance with legal obligations.',
      'privacy.s4.title': '4. AI Processing',
      'privacy.s4.body': 'SynapticSpark uses third-party AI providers (such as OpenAI, Anthropic, Google, and others) to generate text, images, audio, and other content. Prompts and the data you choose to include are sent to these providers for inference. We use providers that contractually commit not to train their models on your data unless you opt in. We do not sell your data to AI providers or anyone else.',
      'privacy.s5.title': '5. Sharing of Information',
      'privacy.s5.intro': 'We share data only as needed and with appropriate safeguards:',
      'privacy.s5.l1': 'Service providers: hosting (cloud infrastructure), email delivery, analytics, payment processing, AI inference, customer support tooling.',
      'privacy.s5.l2': 'Connected platforms you authorize (Shopify, Google, Meta, etc.).',
      'privacy.s5.l3': 'Legal: when required by law, court order, or to protect rights and safety.',
      'privacy.s5.l4': 'Business transfers: if SynapticSpark is involved in a merger, acquisition, or asset sale.',
      'privacy.s5.never': 'We never sell your personal data.',
      'privacy.s6.title': '6. Data Retention',
      'privacy.s6.body': 'We retain personal data while your account is active and for as long as necessary to provide the Service, comply with legal obligations, resolve disputes, and enforce agreements. You may request deletion at any time (see Section 8).',
      'privacy.s7.title': '7. Security',
      'privacy.s7.body': 'We use industry-standard measures: TLS encryption in transit, encryption of OAuth tokens at rest, role-based access controls, regular backups, and audit logging. No system is 100% secure, but we work to protect your data and notify you of significant incidents as required by law.',
      'privacy.s8.title': '8. Your Rights',
      'privacy.s8.intro': 'Depending on your jurisdiction (GDPR, UK GDPR, CCPA/CPRA, LGPD, and similar), you may have the right to:',
      'privacy.s8.l1': 'Access the personal data we hold about you.',
      'privacy.s8.l2': 'Request correction of inaccurate data.',
      'privacy.s8.l3': 'Request deletion of your data.',
      'privacy.s8.l4': 'Object to or restrict certain processing.',
      'privacy.s8.l5': 'Request a portable copy of your data.',
      'privacy.s8.l6': 'Withdraw consent at any time.',
      'privacy.s8.l7': 'Lodge a complaint with your local data protection authority.',
      'privacy.s8.exercise': 'To exercise these rights, contact us at info@synapticsparkai.com or visit our Data Deletion page.',
      'privacy.s9.title': '9. International Transfers',
      'privacy.s9.body': 'Your data may be processed in countries other than your own. When we transfer data internationally, we use appropriate safeguards such as Standard Contractual Clauses approved by the European Commission.',
      'privacy.s10.title': '10. Children',
      'privacy.s10.body': 'The Service is not directed to children under 16. We do not knowingly collect data from children. If you believe a child has provided us data, contact us and we will delete it.',
      'privacy.s11.title': '11. Changes',
      'privacy.s11.body': 'We may update this Privacy Policy from time to time. The "Last updated" date will reflect the latest revision. Material changes will be communicated by email or through the Service.',
      'privacy.s12.title': '12. Contact',
      'privacy.s12.body': 'Questions or requests? Contact our Data Protection team at info@synapticsparkai.com.',

      // TERMS
      'terms.title': 'Terms of Service',
      'terms.updated': 'Last updated: April 25, 2026',
      'terms.intro': 'These Terms of Service ("Terms") govern your access to and use of the SynapticSpark platform, website, mobile applications, integrations, APIs, and related services (collectively, the "Service") provided by SynapticSpark ("we", "us", "our"). By creating an account or using the Service, you agree to these Terms. If you do not agree, do not use the Service.',
      'terms.s1.title': '1. Eligibility & Accounts',
      'terms.s1.body': 'You must be at least 16 years old and able to form a binding contract. You are responsible for keeping your credentials confidential and for all activity under your account. Notify us immediately of any unauthorized use.',
      'terms.s2.title': '2. The Service',
      'terms.s2.body': 'SynapticSpark provides AI-powered tools for marketing automation, including SEO content generation, social media management, creative generation, and paid media analytics. The Service may evolve and we may add, modify, or remove features from time to time.',
      'terms.s3.title': '3. Subscriptions, Trials & Billing',
      'terms.s3.l1': 'Paid plans are billed in advance on a recurring basis (monthly or annual).',
      'terms.s3.l2': 'Free trials may convert into paid subscriptions if not canceled before the trial ends.',
      'terms.s3.l3': 'Fees are non-refundable except where required by law or expressly stated.',
      'terms.s3.l4': 'You can cancel at any time; access continues until the end of the current billing period.',
      'terms.s3.l5': 'We may change pricing with at least 30 days notice for renewals.',
      'terms.s4.title': '4. Your Content',
      'terms.s4.body': 'You retain ownership of all content you upload, generate, or publish through the Service ("Your Content"). You grant SynapticSpark a worldwide, non-exclusive, royalty-free license to host, store, process, transmit, and display Your Content solely to operate and improve the Service. You represent that you have the rights to upload Your Content and that it does not infringe third-party rights.',
      'terms.s5.title': '5. AI-Generated Content',
      'terms.s5.body': 'The Service uses third-party AI models to generate text, images, audio, and other outputs based on your prompts. AI outputs may be inaccurate, biased, or offensive. You are responsible for reviewing AI-generated content before publishing it. You must not rely on AI outputs as a substitute for legal, medical, financial, or professional advice. Subject to your compliance with these Terms, you own the outputs to the extent permitted by applicable law and the underlying model provider\'s terms.',
      'terms.s6.title': '6. Connected Platforms',
      'terms.s6.body': 'When you connect Shopify, Google, Meta, TikTok, or any other third-party platform, you authorize SynapticSpark to access that platform on your behalf within the scopes you approve. You are responsible for complying with each platform\'s terms. We are not responsible for the availability, performance, or policies of third-party platforms.',
      'terms.s7.title': '7. Acceptable Use',
      'terms.s7.intro': 'You agree not to:',
      'terms.s7.l1': 'Use the Service to violate any law or third-party rights.',
      'terms.s7.l2': 'Generate or distribute illegal, defamatory, harassing, hateful, sexually explicit, or deceptive content.',
      'terms.s7.l3': 'Send spam or unsolicited messages, scrape content, or abuse rate limits.',
      'terms.s7.l4': 'Attempt to reverse engineer, decompile, or bypass security controls.',
      'terms.s7.l5': 'Resell or sublicense the Service without our written permission.',
      'terms.s7.l6': 'Use the Service to train competing AI models.',
      'terms.s8.title': '8. Intellectual Property',
      'terms.s8.body': 'SynapticSpark, the platform, software, logos, and trademarks are owned by us or our licensors. We grant you a limited, non-exclusive, non-transferable license to use the Service in accordance with these Terms. All rights not expressly granted are reserved.',
      'terms.s9.title': '9. Suspension & Termination',
      'terms.s9.body': 'We may suspend or terminate your access if you breach these Terms, present a security risk, or fail to pay fees. You may terminate your account at any time. On termination, your access ends and we may delete Your Content after a reasonable retention window, subject to our Privacy Policy.',
      'terms.s10.title': '10. Disclaimers',
      'terms.s10.body': 'THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS, OR THAT AI OUTPUTS WILL BE ACCURATE OR FIT FOR YOUR PURPOSE.',
      'terms.s11.title': '11. Limitation of Liability',
      'terms.s11.body': 'TO THE MAXIMUM EXTENT PERMITTED BY LAW, SYNAPTICSPARK AND ITS AFFILIATES WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUES, DATA, OR GOODWILL. OUR TOTAL LIABILITY ARISING FROM OR RELATED TO THE SERVICE WILL NOT EXCEED THE AMOUNTS YOU PAID US IN THE 12 MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM.',
      'terms.s12.title': '12. Indemnification',
      'terms.s12.body': 'You agree to indemnify and hold harmless SynapticSpark from any claims, damages, liabilities, and expenses (including reasonable legal fees) arising out of Your Content, your use of the Service, or your violation of these Terms.',
      'terms.s13.title': '13. Governing Law',
      'terms.s13.body': 'These Terms are governed by the laws of the jurisdiction where SynapticSpark is established, without regard to conflict of law principles. Any dispute will be resolved in the competent courts of that jurisdiction, unless mandatory consumer law provides otherwise.',
      'terms.s14.title': '14. Changes to Terms',
      'terms.s14.body': 'We may update these Terms from time to time. Material changes will be communicated by email or through the Service at least 14 days before they take effect. Continued use of the Service after the effective date constitutes acceptance.',
      'terms.s15.title': '15. Contact',
      'terms.s15.body': 'Questions about these Terms? Contact us at info@synapticsparkai.com.',

      // COOKIES
      'cookies.title': 'Cookie Policy',
      'cookies.updated': 'Last updated: April 25, 2026',
      'cookies.intro': 'This Cookie Policy explains how SynapticSpark ("we", "us", "our") uses cookies and similar tracking technologies on our website and platform. It should be read together with our Privacy Policy.',
      'cookies.s1.title': '1. What are cookies?',
      'cookies.s1.body': 'Cookies are small text files placed on your device by the websites you visit. They are widely used to make sites work efficiently and to provide reporting information. We also use similar technologies such as local storage, session storage, pixels, and SDKs.',
      'cookies.s2.title': '2. Categories of cookies we use',
      'cookies.s2a.title': 'Strictly necessary',
      'cookies.s2a.body': 'Required for the Service to function: authentication, session management, security, and load balancing. These cannot be disabled.',
      'cookies.s2b.title': 'Functional',
      'cookies.s2b.body': 'Remember your preferences (language, theme, dashboard layout) so we can deliver a personalized experience.',
      'cookies.s2c.title': 'Analytics',
      'cookies.s2c.body': 'Help us understand how the Service is used so we can improve it. We use privacy-respecting analytics tools and aggregate data whenever possible.',
      'cookies.s2d.title': 'Marketing',
      'cookies.s2d.body': 'Used only with your consent to measure the effectiveness of our marketing campaigns and to show relevant content.',
      'cookies.s3.title': '3. Examples of cookies',
      'cookies.tbl.name': 'Name',
      'cookies.tbl.purpose': 'Purpose',
      'cookies.tbl.duration': 'Duration',
      'cookies.tbl.r1': 'Maintains your authenticated session.',
      'cookies.tbl.r1d': 'Session',
      'cookies.tbl.r2': 'Protects against cross-site request forgery.',
      'cookies.tbl.r2d': 'Session',
      'cookies.tbl.r3': 'Stores your language preference.',
      'cookies.tbl.r3d': '1 year',
      'cookies.tbl.r4': 'Stores your dark/light theme preference.',
      'cookies.tbl.r4d': '1 year',
      'cookies.tbl.r5': 'Aggregated usage analytics (Google Analytics).',
      'cookies.tbl.r5d': 'Up to 2 years',
      'cookies.s4.title': '4. Third-party cookies',
      'cookies.s4.body': 'Some cookies are set by third-party services we use (for example, payment processors, analytics providers, or embedded media). These third parties have their own privacy and cookie policies, which we recommend you review.',
      'cookies.s5.title': '5. Managing cookies',
      'cookies.s5.body': 'You can accept, decline, or manage non-essential cookies through the cookie banner shown on first visit. You can also configure your browser to block or delete cookies. Disabling strictly necessary cookies will impair core functionality of the Service.',
      'cookies.s6.title': '6. Changes',
      'cookies.s6.body': 'We may update this Cookie Policy from time to time. The "Last updated" date will reflect any revisions.',
      'cookies.s7.title': '7. Contact',
      'cookies.s7.body': 'For questions, write to info@synapticsparkai.com.',

      // DATA DELETION
      'dataDel.title': 'Data Deletion Request',
      'dataDel.updated': 'Last updated: April 25, 2026',
      'dataDel.intro': 'SynapticSpark respects your right to control your personal data. This page explains how you can request deletion of the personal data we hold about you, including data obtained through integrations such as Shopify, Google, Meta, Instagram, Facebook, and other connected platforms.',
      'dataDel.s1.title': '1. What gets deleted',
      'dataDel.s1.l1': 'Your account profile (name, email, phone, company).',
      'dataDel.s1.l2': 'Content you created or uploaded (posts, prompts, generated assets, configurations).',
      'dataDel.s1.l3': 'OAuth tokens and credentials for connected platforms (Shopify, Google, Meta, etc.).',
      'dataDel.s1.l4': 'Synced data from connected platforms (keywords, blog metadata, campaign metrics).',
      'dataDel.s1.l5': 'Usage logs associated with your account.',
      'dataDel.s2.title': '2. Self-service deletion',
      'dataDel.s2.body': 'If you have an active account, you can delete it from inside the app:',
      'dataDel.s2.l1': 'Sign in at app.synapticsparkai.com.',
      'dataDel.s2.l2': 'Go to Settings → Account → Delete account.',
      'dataDel.s2.l3': 'Confirm the deletion. Your data is queued for permanent removal.',
      'dataDel.s3.title': '3. Email request',
      'dataDel.s3.body': 'If you cannot access your account, send an email to info@synapticsparkai.com from the email address associated with the account, including:',
      'dataDel.s3.l1': 'The subject line: "Data Deletion Request".',
      'dataDel.s3.l2': 'Your full name and registered email address.',
      'dataDel.s3.l3': 'The connected platforms involved (e.g. Shopify store domain) if applicable.',
      'dataDel.s3.verify': 'We may ask for additional information to verify your identity before processing the request.',
      'dataDel.s4.title': '4. Shopify merchants and customers',
      'dataDel.s4.body': 'If you uninstall the SynapticSpark app from your Shopify store, we automatically receive an uninstall webhook and remove your store data within 30 days, in accordance with Shopify\'s GDPR mandatory webhooks (customers/redact, customers/data_request, shop/redact). For ad-hoc requests outside of uninstall, contact us at the email above.',
      'dataDel.s5.title': '5. Timeline',
      'dataDel.s5.body': 'We process verified deletion requests within 30 days. Some data may persist in encrypted backups for a limited rolling window (typically up to 90 days) before being overwritten. Anonymized or aggregated data that cannot be linked back to you may be retained indefinitely.',
      'dataDel.s6.title': '6. Exceptions',
      'dataDel.s6.body': 'We may retain certain data when required by law or for legitimate business reasons, including: (i) tax, accounting and legal obligations; (ii) fraud prevention and security; (iii) enforcing our agreements; (iv) defending legal claims.',
      'dataDel.s7.title': '7. Contact',
      'dataDel.s7.body': 'For any privacy or data deletion question, contact info@synapticsparkai.com.',
    },
    es: {
      'nav.back': 'Volver al Inicio',
      'legal.label': 'Legal',
      'footer.privacy': 'Privacidad',
      'footer.terms': 'Términos',
      'footer.cookies': 'Cookies',
      'footer.dataDeletion': 'Eliminación de Datos',
      'footer.copyright': '© 2026 SynapticSpark. Todos los derechos reservados.',

      // PRIVACY
      'privacy.title': 'Política de Privacidad',
      'privacy.updated': 'Última actualización: 25 de abril de 2026',
      'privacy.intro': 'SynapticSpark ("nosotros", "nuestro") respeta tu privacidad. Esta Política de Privacidad explica cómo recopilamos, usamos, compartimos y protegemos tu información personal cuando usas la plataforma SynapticSpark, nuestro sitio web, aplicaciones móviles, integraciones (incluida la app de SynapticSpark para Shopify), APIs y servicios relacionados (en conjunto, el "Servicio").',
      'privacy.s1.title': '1. Información que Recopilamos',
      'privacy.s1a.title': '1.1 Información que tú proporcionas',
      'privacy.s1a.l1': 'Datos de cuenta: nombre, correo electrónico, contraseña (con hash), nombre de empresa, teléfono.',
      'privacy.s1a.l2': 'Datos de facturación: detalles de pago procesados por nuestro proveedor de pagos (no almacenamos números de tarjeta completos).',
      'privacy.s1a.l3': 'Contenido que subes: posts, imágenes, videos, prompts, recursos de marca, keywords y configuración.',
      'privacy.s1a.l4': 'Comunicaciones de soporte: mensajes y metadatos cuando nos contactas.',
      'privacy.s1b.title': '1.2 Información de plataformas conectadas',
      'privacy.s1b.intro': 'Cuando conectas un servicio de terceros (Shopify, Google Search Console, Meta, Instagram, Facebook, WhatsApp, Google Ads, TikTok Ads, Google Analytics, etc.) recibimos los datos que autorizas, que pueden incluir:',
      'privacy.s1b.l1': 'Shopify: dominio de la tienda, datos de blogs y artículos, metadatos de la tienda, token de acceso OAuth (cifrado en reposo).',
      'privacy.s1b.l2': 'Google Search Console: propiedades de sitio, consultas de búsqueda, impresiones, clics, posiciones.',
      'privacy.s1b.l3': 'Plataformas sociales: IDs de página, posts, comentarios, mensajes y datos de perfil público de usuarios que interactúan con tus canales.',
      'privacy.s1b.l4': 'Plataformas publicitarias: campañas, conjuntos de anuncios, métricas de rendimiento, datos de audiencia.',
      'privacy.s1b.note': 'No recopilamos datos de clientes finales de tu tienda Shopify más allá de lo necesario para entregar la funcionalidad de publicación SEO (blogs, artículos). No accedemos a la información personal identificable de los clientes almacenada en tu base de Shopify.',
      'privacy.s1c.title': '1.3 Información recopilada automáticamente',
      'privacy.s1c.l1': 'Datos de uso: páginas visitadas, funciones utilizadas, marcas de tiempo.',
      'privacy.s1c.l2': 'Datos del dispositivo: navegador, sistema operativo, dirección IP, idioma.',
      'privacy.s1c.l3': 'Cookies y tecnologías similares (consulta nuestra Política de Cookies).',
      'privacy.s2.title': '2. Cómo Usamos la Información',
      'privacy.s2.l1': 'Proveer, operar y mejorar el Servicio.',
      'privacy.s2.l2': 'Generar contenido con IA basado en tus prompts y fuentes de datos conectadas.',
      'privacy.s2.l3': 'Publicar contenido en plataformas que hayas autorizado (por ejemplo, blogs de Shopify).',
      'privacy.s2.l4': 'Autenticar usuarios y prevenir fraude o abuso.',
      'privacy.s2.l5': 'Comunicar avisos transaccionales, alertas de seguridad y actualizaciones de producto.',
      'privacy.s2.l6': 'Cumplir con obligaciones legales.',
      'privacy.s3.title': '3. Base Legal (RGPD)',
      'privacy.s3.body': 'Si estás en el Espacio Económico Europeo, Reino Unido o Suiza, nuestras bases legales son: (i) ejecución de un contrato; (ii) tu consentimiento (que puedes retirar); (iii) intereses legítimos para operar y proteger el Servicio; y (iv) cumplimiento de obligaciones legales.',
      'privacy.s4.title': '4. Procesamiento con IA',
      'privacy.s4.body': 'SynapticSpark utiliza proveedores de IA de terceros (como OpenAI, Anthropic, Google y otros) para generar texto, imágenes, audio y otro contenido. Los prompts y los datos que decidas incluir se envían a estos proveedores para inferencia. Usamos proveedores que se comprometen contractualmente a no entrenar sus modelos con tus datos a menos que optes por ello. No vendemos tus datos a proveedores de IA ni a nadie.',
      'privacy.s5.title': '5. Compartición de Información',
      'privacy.s5.intro': 'Solo compartimos datos cuando es necesario y con las salvaguardas adecuadas:',
      'privacy.s5.l1': 'Proveedores de servicios: hosting (infraestructura cloud), envío de email, analíticas, procesamiento de pagos, inferencia de IA, herramientas de soporte.',
      'privacy.s5.l2': 'Plataformas conectadas que autorizas (Shopify, Google, Meta, etc.).',
      'privacy.s5.l3': 'Legal: cuando lo requiere la ley, una orden judicial, o para proteger derechos y seguridad.',
      'privacy.s5.l4': 'Transferencias de negocio: si SynapticSpark participa en una fusión, adquisición o venta de activos.',
      'privacy.s5.never': 'Nunca vendemos tus datos personales.',
      'privacy.s6.title': '6. Retención de Datos',
      'privacy.s6.body': 'Conservamos los datos personales mientras tu cuenta esté activa y durante el tiempo necesario para prestar el Servicio, cumplir obligaciones legales, resolver disputas y hacer cumplir acuerdos. Puedes solicitar la eliminación en cualquier momento (consulta la Sección 8).',
      'privacy.s7.title': '7. Seguridad',
      'privacy.s7.body': 'Aplicamos medidas estándar de la industria: cifrado TLS en tránsito, cifrado de tokens OAuth en reposo, controles de acceso basados en roles, copias de seguridad regulares y registros de auditoría. Ningún sistema es 100% seguro, pero trabajamos para proteger tus datos y notificarte de incidentes significativos cuando lo exija la ley.',
      'privacy.s8.title': '8. Tus Derechos',
      'privacy.s8.intro': 'Según tu jurisdicción (RGPD, UK GDPR, CCPA/CPRA, LGPD y similares), puedes tener derecho a:',
      'privacy.s8.l1': 'Acceder a los datos personales que tenemos sobre ti.',
      'privacy.s8.l2': 'Solicitar la corrección de datos inexactos.',
      'privacy.s8.l3': 'Solicitar la eliminación de tus datos.',
      'privacy.s8.l4': 'Oponerte o restringir ciertos procesamientos.',
      'privacy.s8.l5': 'Solicitar una copia portable de tus datos.',
      'privacy.s8.l6': 'Retirar el consentimiento en cualquier momento.',
      'privacy.s8.l7': 'Presentar una reclamación ante tu autoridad local de protección de datos.',
      'privacy.s8.exercise': 'Para ejercer estos derechos, escríbenos a info@synapticsparkai.com o visita nuestra página de Eliminación de Datos.',
      'privacy.s9.title': '9. Transferencias Internacionales',
      'privacy.s9.body': 'Tus datos pueden ser procesados en países distintos al tuyo. Cuando transferimos datos internacionalmente, utilizamos salvaguardas apropiadas como las Cláusulas Contractuales Tipo aprobadas por la Comisión Europea.',
      'privacy.s10.title': '10. Menores',
      'privacy.s10.body': 'El Servicio no está dirigido a menores de 16 años. No recopilamos datos de menores conscientemente. Si crees que un menor nos ha proporcionado datos, contáctanos y los eliminaremos.',
      'privacy.s11.title': '11. Cambios',
      'privacy.s11.body': 'Podemos actualizar esta Política de Privacidad de tiempo en tiempo. La fecha de "Última actualización" reflejará la última revisión. Los cambios materiales se comunicarán por email o a través del Servicio.',
      'privacy.s12.title': '12. Contacto',
      'privacy.s12.body': '¿Preguntas o solicitudes? Contacta a nuestro equipo de Protección de Datos en info@synapticsparkai.com.',

      // TERMS
      'terms.title': 'Términos y Condiciones',
      'terms.updated': 'Última actualización: 25 de abril de 2026',
      'terms.intro': 'Estos Términos y Condiciones ("Términos") rigen tu acceso y uso de la plataforma SynapticSpark, sitio web, aplicaciones móviles, integraciones, APIs y servicios relacionados (en conjunto, el "Servicio") proporcionados por SynapticSpark ("nosotros", "nuestro"). Al crear una cuenta o usar el Servicio, aceptas estos Términos. Si no estás de acuerdo, no uses el Servicio.',
      'terms.s1.title': '1. Elegibilidad y Cuentas',
      'terms.s1.body': 'Debes tener al menos 16 años y capacidad para celebrar un contrato vinculante. Eres responsable de mantener la confidencialidad de tus credenciales y de toda la actividad bajo tu cuenta. Notifícanos de inmediato cualquier uso no autorizado.',
      'terms.s2.title': '2. El Servicio',
      'terms.s2.body': 'SynapticSpark provee herramientas con IA para automatización de marketing, incluyendo generación de contenido SEO, gestión de redes sociales, generación creativa y analíticas de medios pagados. El Servicio puede evolucionar y podemos añadir, modificar o eliminar funcionalidades de tiempo en tiempo.',
      'terms.s3.title': '3. Suscripciones, Pruebas y Facturación',
      'terms.s3.l1': 'Los planes de pago se facturan por adelantado de forma recurrente (mensual o anual).',
      'terms.s3.l2': 'Las pruebas gratuitas pueden convertirse en suscripciones pagas si no se cancelan antes de finalizar.',
      'terms.s3.l3': 'Las tarifas no son reembolsables, salvo que la ley o estos Términos lo establezcan explícitamente.',
      'terms.s3.l4': 'Puedes cancelar en cualquier momento; el acceso continúa hasta el final del periodo de facturación actual.',
      'terms.s3.l5': 'Podemos cambiar los precios con al menos 30 días de aviso para renovaciones.',
      'terms.s4.title': '4. Tu Contenido',
      'terms.s4.body': 'Conservas la propiedad de todo el contenido que subes, generas o publicas a través del Servicio ("Tu Contenido"). Otorgas a SynapticSpark una licencia mundial, no exclusiva y libre de regalías para alojar, almacenar, procesar, transmitir y mostrar Tu Contenido con el único fin de operar y mejorar el Servicio. Declaras que tienes los derechos para subir Tu Contenido y que no infringe derechos de terceros.',
      'terms.s5.title': '5. Contenido Generado con IA',
      'terms.s5.body': 'El Servicio usa modelos de IA de terceros para generar texto, imágenes, audio y otros resultados a partir de tus prompts. Los resultados de IA pueden ser inexactos, sesgados u ofensivos. Eres responsable de revisar el contenido generado antes de publicarlo. No debes usar los resultados de IA como sustituto de asesoría legal, médica, financiera o profesional. Sujeto al cumplimiento de estos Términos, eres dueño de los resultados en la medida permitida por la ley aplicable y los términos del proveedor de modelo subyacente.',
      'terms.s6.title': '6. Plataformas Conectadas',
      'terms.s6.body': 'Cuando conectas Shopify, Google, Meta, TikTok o cualquier otra plataforma de terceros, autorizas a SynapticSpark a acceder a esa plataforma en tu nombre dentro de los permisos que apruebas. Eres responsable de cumplir con los términos de cada plataforma. No somos responsables de la disponibilidad, rendimiento o políticas de plataformas de terceros.',
      'terms.s7.title': '7. Uso Aceptable',
      'terms.s7.intro': 'Te comprometes a no:',
      'terms.s7.l1': 'Usar el Servicio para violar leyes o derechos de terceros.',
      'terms.s7.l2': 'Generar o distribuir contenido ilegal, difamatorio, acosador, de odio, sexualmente explícito o engañoso.',
      'terms.s7.l3': 'Enviar spam o mensajes no solicitados, hacer scraping o abusar de límites de uso.',
      'terms.s7.l4': 'Intentar hacer ingeniería inversa, descompilar o eludir controles de seguridad.',
      'terms.s7.l5': 'Revender o sublicenciar el Servicio sin nuestro permiso por escrito.',
      'terms.s7.l6': 'Usar el Servicio para entrenar modelos de IA competidores.',
      'terms.s8.title': '8. Propiedad Intelectual',
      'terms.s8.body': 'SynapticSpark, la plataforma, el software, los logos y las marcas registradas son propiedad nuestra o de nuestros licenciantes. Te otorgamos una licencia limitada, no exclusiva y no transferible para usar el Servicio conforme a estos Términos. Todos los derechos no concedidos expresamente quedan reservados.',
      'terms.s9.title': '9. Suspensión y Terminación',
      'terms.s9.body': 'Podemos suspender o terminar tu acceso si incumples estos Términos, representas un riesgo de seguridad o no pagas las tarifas. Puedes cerrar tu cuenta en cualquier momento. Al terminar, tu acceso finaliza y podemos eliminar Tu Contenido tras un periodo razonable de retención, sujeto a nuestra Política de Privacidad.',
      'terms.s10.title': '10. Renuncias',
      'terms.s10.body': 'EL SERVICIO SE PROVEE "TAL CUAL" Y "SEGÚN DISPONIBILIDAD", SIN GARANTÍAS DE NINGÚN TIPO, EXPRESAS O IMPLÍCITAS, INCLUIDAS GARANTÍAS DE COMERCIABILIDAD, IDONEIDAD PARA UN PROPÓSITO PARTICULAR Y NO INFRACCIÓN. NO GARANTIZAMOS QUE EL SERVICIO SERÁ ININTERRUMPIDO, LIBRE DE ERRORES O LIBRE DE COMPONENTES DAÑINOS, NI QUE LOS RESULTADOS DE IA SERÁN PRECISOS O ADECUADOS PARA TU PROPÓSITO.',
      'terms.s11.title': '11. Limitación de Responsabilidad',
      'terms.s11.body': 'EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY, SYNAPTICSPARK Y SUS AFILIADOS NO SERÁN RESPONSABLES DE DAÑOS INDIRECTOS, INCIDENTALES, ESPECIALES, CONSECUENTES O PUNITIVOS, NI POR PÉRDIDA DE GANANCIAS, INGRESOS, DATOS O REPUTACIÓN. NUESTRA RESPONSABILIDAD TOTAL DERIVADA O RELACIONADA CON EL SERVICIO NO EXCEDERÁ LOS MONTOS QUE NOS PAGASTE EN LOS 12 MESES ANTERIORES AL EVENTO QUE ORIGINÓ EL RECLAMO.',
      'terms.s12.title': '12. Indemnización',
      'terms.s12.body': 'Aceptas indemnizar y mantener indemne a SynapticSpark de cualquier reclamo, daño, responsabilidad y gasto (incluidos honorarios legales razonables) derivados de Tu Contenido, tu uso del Servicio o tu violación de estos Términos.',
      'terms.s13.title': '13. Ley Aplicable',
      'terms.s13.body': 'Estos Términos se rigen por las leyes de la jurisdicción donde SynapticSpark está establecido, sin atender a principios de conflicto de leyes. Cualquier disputa se resolverá en los tribunales competentes de esa jurisdicción, salvo que la ley imperativa de consumo disponga lo contrario.',
      'terms.s14.title': '14. Cambios a los Términos',
      'terms.s14.body': 'Podemos actualizar estos Términos de tiempo en tiempo. Los cambios materiales se comunicarán por email o a través del Servicio con al menos 14 días de antelación. El uso continuado tras la fecha efectiva constituye aceptación.',
      'terms.s15.title': '15. Contacto',
      'terms.s15.body': '¿Preguntas sobre estos Términos? Contáctanos en info@synapticsparkai.com.',

      // COOKIES
      'cookies.title': 'Política de Cookies',
      'cookies.updated': 'Última actualización: 25 de abril de 2026',
      'cookies.intro': 'Esta Política de Cookies explica cómo SynapticSpark ("nosotros", "nuestro") usa cookies y tecnologías de seguimiento similares en nuestro sitio web y plataforma. Debe leerse junto con nuestra Política de Privacidad.',
      'cookies.s1.title': '1. ¿Qué son las cookies?',
      'cookies.s1.body': 'Las cookies son pequeños archivos de texto que los sitios web colocan en tu dispositivo cuando los visitas. Se utilizan ampliamente para que los sitios funcionen de forma eficiente y para proporcionar información de reportes. También usamos tecnologías similares como local storage, session storage, píxeles y SDKs.',
      'cookies.s2.title': '2. Categorías de cookies que usamos',
      'cookies.s2a.title': 'Estrictamente necesarias',
      'cookies.s2a.body': 'Requeridas para que el Servicio funcione: autenticación, gestión de sesión, seguridad y balanceo de carga. No pueden desactivarse.',
      'cookies.s2b.title': 'Funcionales',
      'cookies.s2b.body': 'Recuerdan tus preferencias (idioma, tema, diseño del dashboard) para entregar una experiencia personalizada.',
      'cookies.s2c.title': 'Analíticas',
      'cookies.s2c.body': 'Nos ayudan a entender cómo se usa el Servicio para poder mejorarlo. Usamos herramientas analíticas que respetan la privacidad y agregamos los datos siempre que es posible.',
      'cookies.s2d.title': 'Marketing',
      'cookies.s2d.body': 'Solo se usan con tu consentimiento para medir la efectividad de nuestras campañas y mostrar contenido relevante.',
      'cookies.s3.title': '3. Ejemplos de cookies',
      'cookies.tbl.name': 'Nombre',
      'cookies.tbl.purpose': 'Propósito',
      'cookies.tbl.duration': 'Duración',
      'cookies.tbl.r1': 'Mantiene tu sesión autenticada.',
      'cookies.tbl.r1d': 'Sesión',
      'cookies.tbl.r2': 'Protege contra falsificación de solicitudes entre sitios.',
      'cookies.tbl.r2d': 'Sesión',
      'cookies.tbl.r3': 'Almacena tu preferencia de idioma.',
      'cookies.tbl.r3d': '1 año',
      'cookies.tbl.r4': 'Almacena tu preferencia de tema oscuro/claro.',
      'cookies.tbl.r4d': '1 año',
      'cookies.tbl.r5': 'Analíticas de uso agregadas (Google Analytics).',
      'cookies.tbl.r5d': 'Hasta 2 años',
      'cookies.s4.title': '4. Cookies de terceros',
      'cookies.s4.body': 'Algunas cookies son colocadas por servicios de terceros que utilizamos (por ejemplo, procesadores de pagos, proveedores de analíticas o medios embebidos). Estos terceros tienen sus propias políticas de privacidad y cookies, que recomendamos revisar.',
      'cookies.s5.title': '5. Gestión de cookies',
      'cookies.s5.body': 'Puedes aceptar, rechazar o gestionar las cookies no esenciales mediante el banner de cookies que se muestra en la primera visita. También puedes configurar tu navegador para bloquear o eliminar cookies. Desactivar las cookies estrictamente necesarias afectará funcionalidades clave del Servicio.',
      'cookies.s6.title': '6. Cambios',
      'cookies.s6.body': 'Podemos actualizar esta Política de Cookies de tiempo en tiempo. La fecha de "Última actualización" reflejará cualquier revisión.',
      'cookies.s7.title': '7. Contacto',
      'cookies.s7.body': 'Para preguntas, escribe a info@synapticsparkai.com.',

      // DATA DELETION
      'dataDel.title': 'Solicitud de Eliminación de Datos',
      'dataDel.updated': 'Última actualización: 25 de abril de 2026',
      'dataDel.intro': 'SynapticSpark respeta tu derecho a controlar tus datos personales. Esta página explica cómo solicitar la eliminación de los datos personales que tenemos sobre ti, incluidos los datos obtenidos a través de integraciones como Shopify, Google, Meta, Instagram, Facebook y otras plataformas conectadas.',
      'dataDel.s1.title': '1. Qué se elimina',
      'dataDel.s1.l1': 'Tu perfil de cuenta (nombre, email, teléfono, empresa).',
      'dataDel.s1.l2': 'Contenido que creaste o subiste (posts, prompts, recursos generados, configuraciones).',
      'dataDel.s1.l3': 'Tokens OAuth y credenciales de plataformas conectadas (Shopify, Google, Meta, etc.).',
      'dataDel.s1.l4': 'Datos sincronizados de plataformas conectadas (keywords, metadatos de blog, métricas de campaña).',
      'dataDel.s1.l5': 'Registros de uso asociados a tu cuenta.',
      'dataDel.s2.title': '2. Eliminación autogestionada',
      'dataDel.s2.body': 'Si tienes una cuenta activa, puedes eliminarla desde la app:',
      'dataDel.s2.l1': 'Inicia sesión en app.synapticsparkai.com.',
      'dataDel.s2.l2': 'Ve a Configuración → Cuenta → Eliminar cuenta.',
      'dataDel.s2.l3': 'Confirma la eliminación. Tus datos se ponen en cola para su eliminación permanente.',
      'dataDel.s3.title': '3. Solicitud por email',
      'dataDel.s3.body': 'Si no puedes acceder a tu cuenta, envía un email a info@synapticsparkai.com desde la dirección asociada a la cuenta, incluyendo:',
      'dataDel.s3.l1': 'El asunto: "Solicitud de Eliminación de Datos".',
      'dataDel.s3.l2': 'Tu nombre completo y correo electrónico registrado.',
      'dataDel.s3.l3': 'Las plataformas conectadas involucradas (por ejemplo, dominio de tu tienda Shopify) si aplica.',
      'dataDel.s3.verify': 'Podríamos solicitar información adicional para verificar tu identidad antes de procesar la solicitud.',
      'dataDel.s4.title': '4. Comerciantes y clientes de Shopify',
      'dataDel.s4.body': 'Si desinstalas la app de SynapticSpark de tu tienda Shopify, recibimos automáticamente un webhook de desinstalación y eliminamos los datos de tu tienda en un plazo de 30 días, conforme a los webhooks GDPR obligatorios de Shopify (customers/redact, customers/data_request, shop/redact). Para solicitudes ad-hoc fuera de la desinstalación, contáctanos en el email anterior.',
      'dataDel.s5.title': '5. Plazos',
      'dataDel.s5.body': 'Procesamos solicitudes de eliminación verificadas en un plazo de 30 días. Algunos datos pueden persistir en copias de seguridad cifradas durante una ventana limitada (típicamente hasta 90 días) antes de ser sobrescritos. Los datos anonimizados o agregados que no puedan vincularse contigo pueden conservarse indefinidamente.',
      'dataDel.s6.title': '6. Excepciones',
      'dataDel.s6.body': 'Podemos retener ciertos datos cuando lo exija la ley o por razones legítimas de negocio, incluidas: (i) obligaciones fiscales, contables y legales; (ii) prevención de fraude y seguridad; (iii) ejecución de nuestros acuerdos; (iv) defensa de reclamos legales.',
      'dataDel.s7.title': '7. Contacto',
      'dataDel.s7.body': 'Para cualquier pregunta sobre privacidad o eliminación de datos, contacta info@synapticsparkai.com.',
    },
  };

  let currentLang = localStorage.getItem('lang') || 'en';

  function setLang(lang) {
    currentLang = lang;
    localStorage.setItem('lang', lang);
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      const key = el.getAttribute('data-i18n');
      if (T[lang] && T[lang][key]) {
        el.textContent = T[lang][key];
      }
    });
    const toggle = document.getElementById('langToggle');
    if (toggle) {
      toggle.textContent = lang === 'en' ? 'ES' : 'EN';
    }
  }

  function setTheme(dark) {
    document.documentElement.classList.toggle('dark', dark);
    localStorage.setItem('theme', dark ? 'dark' : 'light');
  }

  document.addEventListener('DOMContentLoaded', function () {
    const langToggle = document.getElementById('langToggle');
    if (langToggle) {
      langToggle.addEventListener('click', function () {
        setLang(currentLang === 'en' ? 'es' : 'en');
      });
    }

    const themeToggle = document.getElementById('themeToggle');
    if (themeToggle) {
      themeToggle.addEventListener('click', function () {
        setTheme(!document.documentElement.classList.contains('dark'));
      });
    }

    const prefersDark = localStorage.getItem('theme') === 'dark' ||
      (!localStorage.getItem('theme') && window.matchMedia('(prefers-color-scheme: dark)').matches);
    setTheme(prefersDark);

    setLang(currentLang);
  });
})();
